team:
   name: X-Code
   members:
      - user: j.vallejosg@uniandes.edu.co
        percentage: 25
      - user: ca.ariasv1@uniandes.edu.co
        percentage: 25
      - user: af.losada@uniandes.edu.co
        percentage: 25
      - user: e.chaparroa@uniandes.edu.co
        percentage: 25
board: https://github.com/orgs/MISW-4301-Desarrollo-Apps-en-la-Nube/projects/163
url: 34.149.74.18
user-management:
  folder: user_management
  port: 3000
  authors:
    - e.chaparroa@uniandes.edu.co
post-management:
  folder: post_management
  port: 3001
  authors:
    - ca.ariasv1@uniandes.edu.co
offer-management:
  folder: offer_management
  port: 3003
  authors:
    - j.vallejosg@uniandes.edu.co
route-management:
  folder: route_management
  port: 3002
  authors:
    - af.losada@uniandes.edu.co
scores:
  folder: scores
  port: 3012
  authors:
    - e.chaparroa@uniandes.edu.co
rf003:
  folder: rf003
  port: 3013
  authors:
    - j.vallejosg@uniandes.edu.co
rf004:
  folder: rf004
  port: 3000
  authors:
    - af.losada@uniandes.edu.co
rf005:
  folder: rf005
  port: 3007
  authors:
    - ca.ariasv1@uniandes.edu.co