name: Merge rf003 feature branch to main

on:
  pull_request:
    branches: [ "main", "**/rf003**"]
    paths:
      - 'rf003/**'

jobs:
  test_rf003:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        working-directory: ./rf003
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Run unit tests
        working-directory: ./rf003
        run: pytest --cov=app test.py -v -s --cov-fail-under=70
